import string

# Remove pucntuations from the string.
def stripped_str(str):
    return str.translate(str.maketrans('', '', string.punctuation))

# Return the error rate of str2 given str1 as the correct text.
# Penalize extra words generated by the ASR, and the missing words.
# WER = (extra + missing) / (extra + missing + matching)
def error_rate(str1, str2):
    if str2 == '':
        return 1.0 # ASR returns empty string
    split1 = stripped_str(str1).lower().split()
    split2 = stripped_str(str2).lower().split()
    correct_count = 0
    wront_count = 0
    for word in split1:
        if word in split2:
            split1.remove(word)
            split2.remove(word)
            correct_count += 1
    wront_count += len(split1)
    wront_count += len(split2)
    return wront_count / (correct_count + wront_count)

if __name__ == '__main__':
	print(error_rate('Hello World!', 'extra hello, world , extra...'))
