/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Sleep.h"

#include "Sleep.tcc"

namespace facebook { namespace windtunnel { namespace treadmill { namespace services { namespace sleep {

}}}}} // facebook::windtunnel::treadmill::services::sleep
namespace apache { namespace thrift {

}} // apache::thrift