/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include "sleep_types.h"
#include <thrift/lib/cpp2/protocol/Protocol.h>
namespace facebook { namespace windtunnel { namespace treadmill { namespace services { namespace sleep {

struct sleep_constants {};

class __attribute__((__deprecated__("sleepConstants suffers from the 'static initialization order fiasco' (https://isocpp.org/wiki/faq/ctors#static-init-order) and may CRASH you program. Instead, use sleep_constants::CONSTANT_NAME()"))) sleepConstants {
 public:
  sleepConstants() {}
};

}}}}} // facebook::windtunnel::treadmill::services::sleep