/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "sleep_types.h"

#include "sleep_types.tcc"

#include <algorithm>

namespace facebook { namespace windtunnel { namespace treadmill { namespace services { namespace sleep {

}}}}} // facebook::windtunnel::treadmill::services::sleep